/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Tesseract
 #	author : miyako
 #	2016/04/04
 #
 # --------------------------------------------------------------------------------*/

#include "leptonica/allheaders.h"
#include "tesseract/baseapi.h"

#define THIS_BUNDLE_ID @"com.4D.4DPlugin.Tesseract"
#define THIS_BUNDLE_NAME L"Tesseract.4DX"

// --- OCR
void OCR_Set_language_folder(sLONG_PTR *pResult, PackagePtr pParams);
void OCR_Get_timeout(sLONG_PTR *pResult, PackagePtr pParams);
void OCR_SET_TIMEOUT(sLONG_PTR *pResult, PackagePtr pParams);
void OCR_Read_image_text(sLONG_PTR *pResult, PackagePtr pParams);
void OCR_Get_language_folder(sLONG_PTR *pResult, PackagePtr pParams);
